---
title: "Chicago Bulls Team Selection"
author: "Joshua Waugh"
output: 
  prettydoc::html_pretty:
    theme: tactile
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

```

### Purpose of analysis

In the 2018-19 season, the Chicago Bulls placed 27th out of 30 in the NBA competition. An analysis has been conducted to determine the best starting 5 players that will play for the new season, based on a variety of statistics that were obtained in the 2018-19 season.

### Methods of analysis

The first step of the analysis was to tidy all datasets, ensuring each variable was in a separate column, each observation was on a separate row, each value was in its own cell, and to remove all missing data. 

The second step was to determine what key metrics were essential for each position. These were sourced by a Basketball handbook from Kingaroy Basketball (1), and further corroborated with an article from BBC Sport Academy (2). The metrics decided were as follows:

1. Point Guard (PG) - Assists, Turnovers and Assist-to-Turnover Ratio
2. Shooting Guard (SG) - Assists, Rebounds and Scoring statistics*
3. Small Forward (SF) - Rebounds, Assists and Scoring statistics*
4. Power Forward (PF) - Rebounds per game and Scoring statistics*
5. Centre (C) - Blocks, Rebounds and Scoring statistics*

*Specific scoring statistics were determined further in the analysis by the use of Multi-Linear Regression.

The third step of the analysis was to filter the main data set according to players, into 5 separate data sets. These sets were filtered down according to the key metrics above, to identify the best performing players in these metrics. The top players also had the most important metric compared to their Salary, showing their value, ie. For each $1000, how many 2-Point Field Goals did the player achieve.

The final step was to determine the player that should be signed for this season, and compare them to the players in that position in the top 5 teams in the 2018-19 season, and compare their statistics.

### Results of analysis


#### Point Guard



#### Shooting Guard



#### Small Forward



#### Power Forward



### Recommendations for the team



### References

1. Basketball, Kingaroy. Basketball positions [Internet. Kingaroy: Kingaroy Amateur Basketball Association; n.d. [cited 2020 April 19]. Available from: https://websites.sportstg.com/get_file.cgi?id=36250836
2. Academy, BBC Sport. Basketball players [Internet]. London: BBC; 2020 [cited 2020 April 19]. Available from: http://news.bbc.co.uk/sportacademy/bsp/hi/basketball/rules/players/html/default.stm
